version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t matheves/node_sample .
      - run:
          name: Run docker image on port 8080
          command : |
            docker run -d -p 8080:8080 --name node_sample_cont matheves/node_sample
      - run:
          name: Curl route 8080
          command: |
            docker run --network container:node_sample_cont appropriate/curl --retry 10 --retry-connrefused http://localhost:8080
      - deploy:
          name: Push application Docker image
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker push matheves/node_sample:latest
